finish first 3 e2e tests
OSU-CS362-W24/final-project-charting pull request #6
Opened 2024-03-13 20:33 UTC by Aic01

2024-03-13 22:13 UTC, jwevans21 requested changes
Left some comments in the code about things that should be made to allow for it to perform the tests with our automation. Also some notes about the use of test ID's.

Don't forget that `start-server-and-test` needs to be added to the dependencies list

2024-03-13 22:13 UTC, jwevans21 commented on package.json
> +    "start_e2e": "serve src",
Is there a reason for including this? It is not used later on and the webpack dev server should be good enough for the testing.

Looks like it can be changed to `webpack serve`.

2024-03-13 22:13 UTC, jwevans21 commented on package.json
> +    "test_e2e": "start-server-and-test start http://localhost:3000 cy:run"
This should be changed to `test:e2e` for compatibility with our automatic tests.

The start could be changed to `start:e2e`

The URL should be changed to port 8080

2024-03-13 22:13 UTC, jwevans21 commented on package.json
> +    "serve": "^14.2.0"
See above about being unused

2024-03-13 22:13 UTC, jwevans21 commented on src/line/line.html
These `data-testid` attributes should probably be using the label text for the inputs and the button content.

2024-03-13 22:59 UTC, Aic01 commented on package.json
> +    "start_e2e": "serve src",
Oh wait, yeah we actually don't need "start_e2e": "serve src", I added that for testing. It's okay we delete that. 

just use "start": "webpack serve --open" is enough

2024-03-13 23:00 UTC, Aic01 commented on package.json
> +    "test_e2e": "start-server-and-test start http://localhost:3000 cy:run"
Yes, that is correct.

2024-03-13 23:01 UTC, Aic01 commented on package.json
> +    "serve": "^14.2.0"
I am actually not sure about this, cuz I basically mimic the style of package.json in the HW-4

2024-03-13 23:15 UTC, jwevans21 commented on package.json
> +    "serve": "^14.2.0"
It is like HW4, but if we use `webpack serve` then `serve` is not needed as a dependency.

2024-03-13 23:18 UTC, Aic01 commented on package.json
> +    "serve": "^14.2.0"
i see, I see. Just changed that.

2024-03-13 23:19 UTC, Aic01 commented on src/line/line.html
actually didnt use the data-testid. So I've deleted them

2024-03-13 23:20 UTC, jwevans21 commented on package.json
> +    "start_e2e": "serve src",
We could also have a `start:e2e` that does not open a browser automatically. I'm not sure how that would impact the GitHub Action testing.

`"start:e2e": "webpack serve"`

2024-03-14 00:12 UTC, Aic01 commented on package.json
> +    "start_e2e": "serve src",
yeah. just added the "start:e2e": "webpack serve". I don't include the "--open" so it won't automatically open the local host page. And I uesed  "npm install --save-dev start-server-and-test" to make sure the     "test:e2e": "start-server-and-test start:e2e http://localhost:8080 cy:run" actually work

2024-03-14 00:14 UTC, jwevans21 approved these changes

2024-03-14 11:03 UTC, ALy3303 approved these changes
We might want to check the title and color for the maintain data test but otherwise, it looks good.

2024-03-15 19:21 UTC, merged